### ISSUE TITLE
pfire-integration-test regressionTest KO

### ISSUE THREAD

**Issue by tartarini** [insigneo-pfire/pFIRE#6]
unexpected issue for a testing configuration with "regression" setting.
Pfire made available using Spack on Sharc:
`spack load pfire@0.4.0`

Running pFIRE on brain_2d.conf
Traceback (most recent call last):
  File "/home/ac1dt/DEVELOPMENT/pFIRE_refactoring/testdata/integration/regression/mask_test_3d/pyvenv36/bin/pfire-integration-test", line 11, in <module>
    load_entry_point('pfire-benchmarking==0.1', 'console_scripts', 'pfire-integration-test')()
  File "/home/ac1dt/DEVELOPMENT/pFIRE_refactoring/benchmarking/pfire_benchmarking/__main__.py", line 41, in main
    testsuite.run_tests()
  File "/home/ac1dt/DEVELOPMENT/pFIRE_refactoring/benchmarking/pfire_benchmarking/testdespatcher.py", line 99, in run_tests
    test.generate_report()
  File "/home/ac1dt/DEVELOPMENT/pFIRE_refactoring/benchmarking/pfire_benchmarking/regression_validate.py", line 86, in generate_report
    self.pfire_reg_path,
AttributeError: 'RegressionTest' object has no attribute 'pfire_reg_path'

Similarly in this config using singularity with pfire 0.4.0

`(venvpy36) Singularity> cd /home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/testdata/integration/regression/brain_2d
(venvpy36) Singularity> 
(venvpy36) Singularity> pfire-integration-test brain_2d_regression.testconf
{'dir': 'brain_2d_regression.testconf', 'output_dir': '.'}
Found "brain2d_regression"
Running pFIRE on brain_2d.conf
Traceback (most recent call last):
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/venvpy36/bin/pfire-integration-test", line 11, in <module>
    load_entry_point('pfire-benchmarking==0.1', 'console_scripts', 'pfire-integration-test')()
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/__main__.py", line 44, in main
    testsuite.run_tests()
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/testdespatcher.py", line 98, in run_tests
    test.run()
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/regression_validate.py", line 71, in run
    self.run_pfire(self.pfire_config)
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/application_routines.py", line 85, in run_pfire
    if not (self.pfire_reg_path or self.pfire_map_path):
AttributeError: 'RegressionTest' object has no attribute 'pfire_reg_path'
(venvpy36) Singularity> pfire-integration-test brain_2d_comparison.testconf 
{'dir': 'brain_2d_comparison.testconf', 'output_dir': '.'}
output_path: brain2d
Found "brain2d"
Running pFIRE on brain_2d.conf
Traceback (most recent call last):
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/venvpy36/bin/pfire-integration-test", line 11, in <module>
    load_entry_point('pfire-benchmarking==0.1', 'console_scripts', 'pfire-integration-test')()
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/__main__.py", line 44, in main
    testsuite.run_tests()
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/testdespatcher.py", line 98, in run_tests
    test.run()
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/cross_validate.py", line 58, in run
    self.run_pfire(self.pfire_config)
  File "/home/tartarini/DEVELOP/INSIGNEO/insigneo-pfire/pFIRE/benchmarking/pfire_benchmarking/application_routines.py", line 85, in run_pfire
    if not (self.pfire_reg_path or self.pfire_map_path):
AttributeError: 'ComparisonTest' object has no attribute 'pfire_reg_path'

`

**Comment by tartarini** [comment]
the regression tests do not work with v0.4.0/v0.5.0.

`
Application_routines.py ->
    def run_pfire(self, config_path, comm_size=1):
`
parses pfire log searching for tokens present only in branch Master

**Comment by tartarini** [comment]
change code philosophy by reading from configuration file as first choice, instead of parsing log file
